### ISSUE TITLE
screenshot of "use this template" button doesn't match what I see

### ISSUE THREAD

**Issue by paciorek** [jasa-acs/repro-template-dev#9]
@stephaniehicks when I look at https://github.com/jasa-acs/repro-template, it doesn't really match the screenshot/image that you link to in the README. Can you see if it matches for you?

**Comment by stephaniehicks** [comment]
hi @paciorek -- agreed. That was intentional. The screenshot / image that I linked to in the README are from the GitHub instructions for creating a repository from template, which you can see here: 

- https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template 

I link to the URL in the sentence below the screenshot / image: 

> "From there, author(s) can [follow these instructions](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template). However do not optionally select "Include all branches" as you do not need this for your own projects."

I felt like this was a more advantageous way to go (vs taking a screenshot of our own repo) as I fear our repo will likely change over time and we'll have to keep maintaining the screenshot / image to stay in sync. I'd rather just link to an image of a template repo that GitHub created specifically designed to teach others on how to create a repository from a template. 

What do you think?

**Comment by paciorek** [comment]
Sure, fine by me.
